[browser]
gatherUsageStats = false

[server]
headless = true
port = 5000
address = "0.0.0.0"
maxUploadSize = 200

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"