
[server]
port = 8080
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 8080
gatherUsageStats = false

[global]
developmentMode = false
