# Database configuration for production
[database]
host = "dpg-d1h53rffte5s739b1i40-a.oregon-postgres.render.com"
port = 5432
database = "dwg_analyzer_pro"
username = "de_de"
password = "PUPB8V0s2b3bvNZUblolz7d6UM9bcBzb"
url = "postgresql://de_de:PUPB8V0s2b3bvNZUblolz7d6UM9bcBzb@dpg-d1h53rffte5s739b1i40-a.oregon-postgres.render.com/dwg_analyzer_pro"